name: CMake

on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    env:
      DECODE_ACARS_APPS: ${{github.workspace}}/build/examples/decode_acars_apps
      SAMPLE_ADSC: "d B6 /BOMASAI.ADS.VT-ANB072501A070A988CA73248F0E5DC10200000F5EE1ABC000102B885E0A19F5"
      SAMPLE_CPDLC: "d BA /AKLCDYA.AT1.B-2727A0D5470C3D803BA464FAE2A15530DA2448312641AB425383320C74009CE009090A2CCA506AA61941DCA5005763"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packaged dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get update; fi
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get install libxml2-dev; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew update; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew install libxml2; fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: ADS-C test
      run: |
        ${DECODE_ACARS_APPS} ${SAMPLE_ADSC}
        ${DECODE_ACARS_APPS} ${SAMPLE_ADSC} | grep -q "Temperature: -62.75 C"
    - name: CPDLC test
      run: |
        ${DECODE_ACARS_APPS} ${SAMPLE_CPDLC}
        ${DECODE_ACARS_APPS} ${SAMPLE_CPDLC} | grep -q "Flight level: 360"
