name: CMake

on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04, macos-latest, macos-11 ]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      DECODE_ACARS_APPS: ${{github.workspace}}/build/examples/decode_acars_apps
      SAMPLE_ADSC: "d B6 /BOMASAI.ADS.VT-ANB072501A070A988CA73248F0E5DC10200000F5EE1ABC000102B885E0A19F5"
      SAMPLE_CPDLC: "d BA /AKLCDYA.AT1.B-2727A0D5470C3D803BA464FAE2A15530DA2448312641AB425383320C74009CE009090A2CCA506AA61941DCA5005763"
      SAMPLE_OHMA: "d H1 OHMAeJy1kV1vgjAUhv/K0mshfPjJHUOMZFQJsjk3FtNptzUpaEo1WYz/fceizikuuxlwc9rnfc85Lxu0pqJgixw5yNINVEMZLQryTqHepGjGGc1lME+Rk6JhH7spqqUHpEskVReWYdmaYWqGlZgNBz7D1BtW50nBcyIJUGBGmFhyktMCymeoJWF8sMpeqVAuiaeFk32DxZxydajKN87eP+RBNqdLIuRKUBf8FkJ6ACs2THpY8UQItib8/N6fPAQnfqet+xM7Hqs7uoaFD61U4XFSFPsIoDPJqBRs9g0nLPtDDCX6uaTHKKfYT8p1WV5Iks+OweRk75jJCFY9DAokbLUqsV00L9vaT9ojgj+U//MCr+v1CkW84rSg8pqoZbdusPvoOI7bx5rdwrdhUzN2TyeEQ3PnWHr+W1QJNqdeGETY7wbuYOrF98HIn8ZR8nt0IEt8HJmQcvdsLdus6x27fZbFXmBVChq63b4i6Aa9XoXG0FsXigibUeyPRvexXzlXXW/+IqmcDAazm+ca17vrhcPx1cmsRnv328p3i7ZfOT9AmQ=="
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install packaged dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get update; fi
        if [[ "$RUNNER_OS" == "Linux" ]]; then sudo apt-get install libxml2-dev libjansson-dev; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew update; fi
        if [[ "$RUNNER_OS" == "macOS" ]]; then brew install libxml2 jansson; fi

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: ADS-C test
      run: |
        ${DECODE_ACARS_APPS} ${SAMPLE_ADSC}
        ${DECODE_ACARS_APPS} ${SAMPLE_ADSC} | grep -q "Temperature: -62.75 C"
    - name: CPDLC test
      run: |
        ${DECODE_ACARS_APPS} ${SAMPLE_CPDLC}
        ${DECODE_ACARS_APPS} ${SAMPLE_CPDLC} | grep -q "Flight level: 360"
    - name: OHMA test
      run: |
        ${DECODE_ACARS_APPS} ${SAMPLE_OHMA}
        ${DECODE_ACARS_APPS} ${SAMPLE_OHMA} | grep -q "737 MAX:::AHM-37MBL6-000009L:::1"
