/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSTurbulence_H_
#define	_FANSTurbulence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSTurbulence {
	FANSTurbulence_light	= 0,
	FANSTurbulence_moderate	= 1,
	FANSTurbulence_severe	= 2
} e_FANSTurbulence;

/* FANSTurbulence */
typedef long	 FANSTurbulence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSTurbulence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSTurbulence;
extern const asn_INTEGER_specifics_t asn_SPC_FANSTurbulence_specs_1;
asn_struct_free_f FANSTurbulence_free;
asn_struct_print_f FANSTurbulence_print;
asn_constr_check_f FANSTurbulence_constraint;
ber_type_decoder_f FANSTurbulence_decode_ber;
der_type_encoder_f FANSTurbulence_encode_der;
xer_type_decoder_f FANSTurbulence_decode_xer;
xer_type_encoder_f FANSTurbulence_encode_xer;
jer_type_encoder_f FANSTurbulence_encode_jer;
oer_type_decoder_f FANSTurbulence_decode_oer;
oer_type_encoder_f FANSTurbulence_encode_oer;
per_type_decoder_f FANSTurbulence_decode_uper;
per_type_encoder_f FANSTurbulence_encode_uper;
per_type_decoder_f FANSTurbulence_decode_aper;
per_type_encoder_f FANSTurbulence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTurbulence_H_ */
#include <asn_internal.h>
