/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSTimeSpeedSpeed.h"

asn_TYPE_member_t asn_MBR_FANSTimeSpeedSpeed_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeSpeedSpeed, time),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSTime,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeSpeedSpeed, speed_seqOf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSSpeedSpeed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"speed-seqOf"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSTimeSpeedSpeed_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSTimeSpeedSpeed_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* time */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* speed-seqOf */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSTimeSpeedSpeed_specs_1 = {
	sizeof(struct FANSTimeSpeedSpeed),
	offsetof(struct FANSTimeSpeedSpeed, _asn_ctx),
	asn_MAP_FANSTimeSpeedSpeed_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSTimeSpeedSpeed = {
	"FANSTimeSpeedSpeed",
	"FANSTimeSpeedSpeed",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSTimeSpeedSpeed_tags_1,
	sizeof(asn_DEF_FANSTimeSpeedSpeed_tags_1)
		/sizeof(asn_DEF_FANSTimeSpeedSpeed_tags_1[0]), /* 1 */
	asn_DEF_FANSTimeSpeedSpeed_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSTimeSpeedSpeed_tags_1)
		/sizeof(asn_DEF_FANSTimeSpeedSpeed_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSTimeSpeedSpeed_1,
	2,	/* Elements count */
	&asn_SPC_FANSTimeSpeedSpeed_specs_1	/* Additional specs */
};

