/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSTimeTime_H_
#define	_FANSTimeTime_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSTime;

/* FANSTimeTime */
typedef struct FANSTimeTime {
	A_SEQUENCE_OF(struct FANSTime) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSTimeTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeTime;
extern asn_SET_OF_specifics_t asn_SPC_FANSTimeTime_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSTimeTime_1[1];
extern asn_per_constraints_t asn_PER_type_FANSTimeTime_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSTime.h"

#endif	/* _FANSTimeTime_H_ */
#include "asn_internal.h"
