/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSATCUplinkMsgElementId_H_
#define	_FANSATCUplinkMsgElementId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "FANSATISCode.h"
#include "FANSErrorInformation.h"
#include "FANSICAOfacilityDesignation.h"
#include "FANSFreeText.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSATCUplinkMsgElementId_PR {
	FANSATCUplinkMsgElementId_PR_NOTHING,	/* No components present */
	FANSATCUplinkMsgElementId_PR_uM0NULL,
	FANSATCUplinkMsgElementId_PR_uM1NULL,
	FANSATCUplinkMsgElementId_PR_uM2NULL,
	FANSATCUplinkMsgElementId_PR_uM3NULL,
	FANSATCUplinkMsgElementId_PR_uM4NULL,
	FANSATCUplinkMsgElementId_PR_uM5NULL,
	FANSATCUplinkMsgElementId_PR_uM6Altitude,
	FANSATCUplinkMsgElementId_PR_uM7Time,
	FANSATCUplinkMsgElementId_PR_uM8Position,
	FANSATCUplinkMsgElementId_PR_uM9Time,
	FANSATCUplinkMsgElementId_PR_uM10Position,
	FANSATCUplinkMsgElementId_PR_uM11Time,
	FANSATCUplinkMsgElementId_PR_uM12Position,
	FANSATCUplinkMsgElementId_PR_uM13TimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM14PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM15TimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM16PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM17TimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM18PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM19Altitude,
	FANSATCUplinkMsgElementId_PR_uM20Altitude,
	FANSATCUplinkMsgElementId_PR_uM21TimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM22PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM23Altitude,
	FANSATCUplinkMsgElementId_PR_uM24TimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM25PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM26AltitudeTime,
	FANSATCUplinkMsgElementId_PR_uM27AltitudePosition,
	FANSATCUplinkMsgElementId_PR_uM28AltitudeTime,
	FANSATCUplinkMsgElementId_PR_uM29AltitudePosition,
	FANSATCUplinkMsgElementId_PR_uM30AltitudeAltitude,
	FANSATCUplinkMsgElementId_PR_uM31AltitudeAltitude,
	FANSATCUplinkMsgElementId_PR_uM32AltitudeAltitude,
	FANSATCUplinkMsgElementId_PR_uM33Altitude,
	FANSATCUplinkMsgElementId_PR_uM34Altitude,
	FANSATCUplinkMsgElementId_PR_uM35Altitude,
	FANSATCUplinkMsgElementId_PR_uM36Altitude,
	FANSATCUplinkMsgElementId_PR_uM37Altitude,
	FANSATCUplinkMsgElementId_PR_uM38Altitude,
	FANSATCUplinkMsgElementId_PR_uM39Altitude,
	FANSATCUplinkMsgElementId_PR_uM40Altitude,
	FANSATCUplinkMsgElementId_PR_uM41Altitude,
	FANSATCUplinkMsgElementId_PR_uM42PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM43PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM44PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM45PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM46PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM47PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM48PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM49PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM50PositionAltitudeAltitude,
	FANSATCUplinkMsgElementId_PR_uM51PositionTime,
	FANSATCUplinkMsgElementId_PR_uM52PositionTime,
	FANSATCUplinkMsgElementId_PR_uM53PositionTime,
	FANSATCUplinkMsgElementId_PR_uM54PositionTimeTime,
	FANSATCUplinkMsgElementId_PR_uM55PositionSpeed,
	FANSATCUplinkMsgElementId_PR_uM56PositionSpeed,
	FANSATCUplinkMsgElementId_PR_uM57PositionSpeed,
	FANSATCUplinkMsgElementId_PR_uM58PositionTimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM59PositionTimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM60PositionTimeAltitude,
	FANSATCUplinkMsgElementId_PR_uM61PositionAltitudeSpeed,
	FANSATCUplinkMsgElementId_PR_uM62TimePositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM63TimePositionAltitudeSpeed,
	FANSATCUplinkMsgElementId_PR_uM64DistanceOffsetDirection,
	FANSATCUplinkMsgElementId_PR_uM65PositionDistanceOffsetDirection,
	FANSATCUplinkMsgElementId_PR_uM66TimeDistanceOffsetDirection,
	FANSATCUplinkMsgElementId_PR_uM67NULL,
	FANSATCUplinkMsgElementId_PR_uM68Position,
	FANSATCUplinkMsgElementId_PR_uM69Time,
	FANSATCUplinkMsgElementId_PR_uM70Position,
	FANSATCUplinkMsgElementId_PR_uM71Time,
	FANSATCUplinkMsgElementId_PR_uM72NULL,
	FANSATCUplinkMsgElementId_PR_uM73Predepartureclearance,
	FANSATCUplinkMsgElementId_PR_uM74Position,
	FANSATCUplinkMsgElementId_PR_uM75Position,
	FANSATCUplinkMsgElementId_PR_uM76TimePosition,
	FANSATCUplinkMsgElementId_PR_uM77PositionPosition,
	FANSATCUplinkMsgElementId_PR_uM78AltitudePosition,
	FANSATCUplinkMsgElementId_PR_uM79PositionRouteClearance,
	FANSATCUplinkMsgElementId_PR_uM80RouteClearance,
	FANSATCUplinkMsgElementId_PR_uM81ProcedureName,
	FANSATCUplinkMsgElementId_PR_uM82DistanceOffsetDirection,
	FANSATCUplinkMsgElementId_PR_uM83PositionRouteClearance,
	FANSATCUplinkMsgElementId_PR_uM84PositionProcedureName,
	FANSATCUplinkMsgElementId_PR_uM85RouteClearance,
	FANSATCUplinkMsgElementId_PR_uM86PositionRouteClearance,
	FANSATCUplinkMsgElementId_PR_uM87Position,
	FANSATCUplinkMsgElementId_PR_uM88PositionPosition,
	FANSATCUplinkMsgElementId_PR_uM89TimePosition,
	FANSATCUplinkMsgElementId_PR_uM90AltitudePosition,
	FANSATCUplinkMsgElementId_PR_uM91HoldClearance,
	FANSATCUplinkMsgElementId_PR_uM92PositionAltitude,
	FANSATCUplinkMsgElementId_PR_uM93Time,
	FANSATCUplinkMsgElementId_PR_uM94DirectionDegrees,
	FANSATCUplinkMsgElementId_PR_uM95DirectionDegrees,
	FANSATCUplinkMsgElementId_PR_uM96NULL,
	FANSATCUplinkMsgElementId_PR_uM97PositionDegrees,
	FANSATCUplinkMsgElementId_PR_uM98DirectionDegrees,
	FANSATCUplinkMsgElementId_PR_uM99ProcedureName,
	FANSATCUplinkMsgElementId_PR_uM100TimeSpeed,
	FANSATCUplinkMsgElementId_PR_uM101PositionSpeed,
	FANSATCUplinkMsgElementId_PR_uM102AltitudeSpeed,
	FANSATCUplinkMsgElementId_PR_uM103TimeSpeedSpeed,
	FANSATCUplinkMsgElementId_PR_uM104PositionSpeedSpeed,
	FANSATCUplinkMsgElementId_PR_uM105AltitudeSpeedSpeed,
	FANSATCUplinkMsgElementId_PR_uM106Speed,
	FANSATCUplinkMsgElementId_PR_uM107NULL,
	FANSATCUplinkMsgElementId_PR_uM108Speed,
	FANSATCUplinkMsgElementId_PR_uM109Speed,
	FANSATCUplinkMsgElementId_PR_uM110SpeedSpeed,
	FANSATCUplinkMsgElementId_PR_uM111Speed,
	FANSATCUplinkMsgElementId_PR_uM112Speed,
	FANSATCUplinkMsgElementId_PR_uM113Speed,
	FANSATCUplinkMsgElementId_PR_uM114Speed,
	FANSATCUplinkMsgElementId_PR_uM115Speed,
	FANSATCUplinkMsgElementId_PR_uM116NULL,
	FANSATCUplinkMsgElementId_PR_uM117ICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM118PositionICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM119TimeICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM120ICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM121PositionICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM122TimeICAOunitnameFrequency,
	FANSATCUplinkMsgElementId_PR_uM123BeaconCode,
	FANSATCUplinkMsgElementId_PR_uM124NULL,
	FANSATCUplinkMsgElementId_PR_uM125NULL,
	FANSATCUplinkMsgElementId_PR_uM126NULL,
	FANSATCUplinkMsgElementId_PR_uM127NULL,
	FANSATCUplinkMsgElementId_PR_uM128Altitude,
	FANSATCUplinkMsgElementId_PR_uM129Altitude,
	FANSATCUplinkMsgElementId_PR_uM130Position,
	FANSATCUplinkMsgElementId_PR_uM131NULL,
	FANSATCUplinkMsgElementId_PR_uM132NULL,
	FANSATCUplinkMsgElementId_PR_uM133NULL,
	FANSATCUplinkMsgElementId_PR_uM134NULL,
	FANSATCUplinkMsgElementId_PR_uM135NULL,
	FANSATCUplinkMsgElementId_PR_uM136NULL,
	FANSATCUplinkMsgElementId_PR_uM137NULL,
	FANSATCUplinkMsgElementId_PR_uM138NULL,
	FANSATCUplinkMsgElementId_PR_uM139NULL,
	FANSATCUplinkMsgElementId_PR_uM140NULL,
	FANSATCUplinkMsgElementId_PR_uM141NULL,
	FANSATCUplinkMsgElementId_PR_uM142NULL,
	FANSATCUplinkMsgElementId_PR_uM143NULL,
	FANSATCUplinkMsgElementId_PR_uM144NULL,
	FANSATCUplinkMsgElementId_PR_uM145NULL,
	FANSATCUplinkMsgElementId_PR_uM146NULL,
	FANSATCUplinkMsgElementId_PR_uM147NULL,
	FANSATCUplinkMsgElementId_PR_uM148Altitude,
	FANSATCUplinkMsgElementId_PR_uM149AltitudePosition,
	FANSATCUplinkMsgElementId_PR_uM150AltitudeTime,
	FANSATCUplinkMsgElementId_PR_uM151Speed,
	FANSATCUplinkMsgElementId_PR_uM152DistanceOffsetDirection,
	FANSATCUplinkMsgElementId_PR_uM153Altimeter,
	FANSATCUplinkMsgElementId_PR_uM154NULL,
	FANSATCUplinkMsgElementId_PR_uM155Position,
	FANSATCUplinkMsgElementId_PR_uM156NULL,
	FANSATCUplinkMsgElementId_PR_uM157Frequency,
	FANSATCUplinkMsgElementId_PR_uM158ATISCode,
	FANSATCUplinkMsgElementId_PR_uM159ErrorInformation,
	FANSATCUplinkMsgElementId_PR_uM160ICAOfacilitydesignation,
	FANSATCUplinkMsgElementId_PR_uM161NULL,
	FANSATCUplinkMsgElementId_PR_uM162NULL,
	FANSATCUplinkMsgElementId_PR_uM163ICAOfacilitydesignationTp4table,
	FANSATCUplinkMsgElementId_PR_uM164NULL,
	FANSATCUplinkMsgElementId_PR_uM165NULL,
	FANSATCUplinkMsgElementId_PR_uM166NULL,
	FANSATCUplinkMsgElementId_PR_uM167NULL,
	FANSATCUplinkMsgElementId_PR_uM168NULL,
	FANSATCUplinkMsgElementId_PR_uM169FreeText,
	FANSATCUplinkMsgElementId_PR_uM170FreeText,
	FANSATCUplinkMsgElementId_PR_uM171VerticalRate,
	FANSATCUplinkMsgElementId_PR_uM172VerticalRate,
	FANSATCUplinkMsgElementId_PR_uM173VerticalRate,
	FANSATCUplinkMsgElementId_PR_uM174VerticalRate,
	FANSATCUplinkMsgElementId_PR_uM175Altitude,
	FANSATCUplinkMsgElementId_PR_uM176NULL,
	FANSATCUplinkMsgElementId_PR_uM177NULL,
	FANSATCUplinkMsgElementId_PR_uM178NULL,
	FANSATCUplinkMsgElementId_PR_uM179NULL,
	FANSATCUplinkMsgElementId_PR_uM180AltitudeAltitude,
	FANSATCUplinkMsgElementId_PR_uM181ToFromPosition,
	FANSATCUplinkMsgElementId_PR_uM182NULL
} FANSATCUplinkMsgElementId_PR;

/* Forward declarations */
struct FANSAltitude;
struct FANSTime;
struct FANSPosition;
struct FANSTimeAltitude;
struct FANSPositionAltitude;
struct FANSAltitudeTime;
struct FANSAltitudePosition;
struct FANSAltitudeAltitude;
struct FANSPositionAltitudeAltitude;
struct FANSPositionTime;
struct FANSPositionTimeTime;
struct FANSPositionSpeed;
struct FANSPositionTimeAltitude;
struct FANSPositionAltitudeSpeed;
struct FANSTimePositionAltitude;
struct FANSTimePositionAltitudeSpeed;
struct FANSDistanceOffsetDirection;
struct FANSPositionDistanceOffsetDirection;
struct FANSTimeDistanceOffsetDirection;
struct FANSPredepartureClearance;
struct FANSTimePosition;
struct FANSPositionPosition;
struct FANSPositionRouteClearance;
struct FANSRouteClearance;
struct FANSProcedureName;
struct FANSPositionProcedureName;
struct FANSHoldClearance;
struct FANSDirectionDegrees;
struct FANSPositionDegrees;
struct FANSTimeSpeed;
struct FANSAltitudeSpeed;
struct FANSTimeSpeedSpeed;
struct FANSPositionSpeedSpeed;
struct FANSAltitudeSpeedSpeed;
struct FANSSpeed;
struct FANSSpeedSpeed;
struct FANSICAOUnitNameFrequency;
struct FANSPositionICAOUnitNameFrequency;
struct FANSTimeICAOunitnameFrequency;
struct FANSBeaconCode;
struct FANSAltimeter;
struct FANSFrequency;
struct FANSICAOFacilityDesignationTp4Table;
struct FANSVerticalRate;
struct FANSToFromPosition;

/* FANSATCUplinkMsgElementId */
typedef struct FANSATCUplinkMsgElementId {
	FANSATCUplinkMsgElementId_PR present;
	union FANSATCUplinkMsgElementId_u {
		NULL_t	 uM0NULL;
		NULL_t	 uM1NULL;
		NULL_t	 uM2NULL;
		NULL_t	 uM3NULL;
		NULL_t	 uM4NULL;
		NULL_t	 uM5NULL;
		struct FANSAltitude	*uM6Altitude;
		struct FANSTime	*uM7Time;
		struct FANSPosition	*uM8Position;
		struct FANSTime	*uM9Time;
		struct FANSPosition	*uM10Position;
		struct FANSTime	*uM11Time;
		struct FANSPosition	*uM12Position;
		struct FANSTimeAltitude	*uM13TimeAltitude;
		struct FANSPositionAltitude	*uM14PositionAltitude;
		struct FANSTimeAltitude	*uM15TimeAltitude;
		struct FANSPositionAltitude	*uM16PositionAltitude;
		struct FANSTimeAltitude	*uM17TimeAltitude;
		struct FANSPositionAltitude	*uM18PositionAltitude;
		struct FANSAltitude	*uM19Altitude;
		struct FANSAltitude	*uM20Altitude;
		struct FANSTimeAltitude	*uM21TimeAltitude;
		struct FANSPositionAltitude	*uM22PositionAltitude;
		struct FANSAltitude	*uM23Altitude;
		struct FANSTimeAltitude	*uM24TimeAltitude;
		struct FANSPositionAltitude	*uM25PositionAltitude;
		struct FANSAltitudeTime	*uM26AltitudeTime;
		struct FANSAltitudePosition	*uM27AltitudePosition;
		struct FANSAltitudeTime	*uM28AltitudeTime;
		struct FANSAltitudePosition	*uM29AltitudePosition;
		struct FANSAltitudeAltitude	*uM30AltitudeAltitude;
		struct FANSAltitudeAltitude	*uM31AltitudeAltitude;
		struct FANSAltitudeAltitude	*uM32AltitudeAltitude;
		struct FANSAltitude	*uM33Altitude;
		struct FANSAltitude	*uM34Altitude;
		struct FANSAltitude	*uM35Altitude;
		struct FANSAltitude	*uM36Altitude;
		struct FANSAltitude	*uM37Altitude;
		struct FANSAltitude	*uM38Altitude;
		struct FANSAltitude	*uM39Altitude;
		struct FANSAltitude	*uM40Altitude;
		struct FANSAltitude	*uM41Altitude;
		struct FANSPositionAltitude	*uM42PositionAltitude;
		struct FANSPositionAltitude	*uM43PositionAltitude;
		struct FANSPositionAltitude	*uM44PositionAltitude;
		struct FANSPositionAltitude	*uM45PositionAltitude;
		struct FANSPositionAltitude	*uM46PositionAltitude;
		struct FANSPositionAltitude	*uM47PositionAltitude;
		struct FANSPositionAltitude	*uM48PositionAltitude;
		struct FANSPositionAltitude	*uM49PositionAltitude;
		struct FANSPositionAltitudeAltitude	*uM50PositionAltitudeAltitude;
		struct FANSPositionTime	*uM51PositionTime;
		struct FANSPositionTime	*uM52PositionTime;
		struct FANSPositionTime	*uM53PositionTime;
		struct FANSPositionTimeTime	*uM54PositionTimeTime;
		struct FANSPositionSpeed	*uM55PositionSpeed;
		struct FANSPositionSpeed	*uM56PositionSpeed;
		struct FANSPositionSpeed	*uM57PositionSpeed;
		struct FANSPositionTimeAltitude	*uM58PositionTimeAltitude;
		struct FANSPositionTimeAltitude	*uM59PositionTimeAltitude;
		struct FANSPositionTimeAltitude	*uM60PositionTimeAltitude;
		struct FANSPositionAltitudeSpeed	*uM61PositionAltitudeSpeed;
		struct FANSTimePositionAltitude	*uM62TimePositionAltitude;
		struct FANSTimePositionAltitudeSpeed	*uM63TimePositionAltitudeSpeed;
		struct FANSDistanceOffsetDirection	*uM64DistanceOffsetDirection;
		struct FANSPositionDistanceOffsetDirection	*uM65PositionDistanceOffsetDirection;
		struct FANSTimeDistanceOffsetDirection	*uM66TimeDistanceOffsetDirection;
		NULL_t	 uM67NULL;
		struct FANSPosition	*uM68Position;
		struct FANSTime	*uM69Time;
		struct FANSPosition	*uM70Position;
		struct FANSTime	*uM71Time;
		NULL_t	 uM72NULL;
		struct FANSPredepartureClearance	*uM73Predepartureclearance;
		struct FANSPosition	*uM74Position;
		struct FANSPosition	*uM75Position;
		struct FANSTimePosition	*uM76TimePosition;
		struct FANSPositionPosition	*uM77PositionPosition;
		struct FANSAltitudePosition	*uM78AltitudePosition;
		struct FANSPositionRouteClearance	*uM79PositionRouteClearance;
		struct FANSRouteClearance	*uM80RouteClearance;
		struct FANSProcedureName	*uM81ProcedureName;
		struct FANSDistanceOffsetDirection	*uM82DistanceOffsetDirection;
		struct FANSPositionRouteClearance	*uM83PositionRouteClearance;
		struct FANSPositionProcedureName	*uM84PositionProcedureName;
		struct FANSRouteClearance	*uM85RouteClearance;
		struct FANSPositionRouteClearance	*uM86PositionRouteClearance;
		struct FANSPosition	*uM87Position;
		struct FANSPositionPosition	*uM88PositionPosition;
		struct FANSTimePosition	*uM89TimePosition;
		struct FANSAltitudePosition	*uM90AltitudePosition;
		struct FANSHoldClearance	*uM91HoldClearance;
		struct FANSPositionAltitude	*uM92PositionAltitude;
		struct FANSTime	*uM93Time;
		struct FANSDirectionDegrees	*uM94DirectionDegrees;
		struct FANSDirectionDegrees	*uM95DirectionDegrees;
		NULL_t	 uM96NULL;
		struct FANSPositionDegrees	*uM97PositionDegrees;
		struct FANSDirectionDegrees	*uM98DirectionDegrees;
		struct FANSProcedureName	*uM99ProcedureName;
		struct FANSTimeSpeed	*uM100TimeSpeed;
		struct FANSPositionSpeed	*uM101PositionSpeed;
		struct FANSAltitudeSpeed	*uM102AltitudeSpeed;
		struct FANSTimeSpeedSpeed	*uM103TimeSpeedSpeed;
		struct FANSPositionSpeedSpeed	*uM104PositionSpeedSpeed;
		struct FANSAltitudeSpeedSpeed	*uM105AltitudeSpeedSpeed;
		struct FANSSpeed	*uM106Speed;
		NULL_t	 uM107NULL;
		struct FANSSpeed	*uM108Speed;
		struct FANSSpeed	*uM109Speed;
		struct FANSSpeedSpeed	*uM110SpeedSpeed;
		struct FANSSpeed	*uM111Speed;
		struct FANSSpeed	*uM112Speed;
		struct FANSSpeed	*uM113Speed;
		struct FANSSpeed	*uM114Speed;
		struct FANSSpeed	*uM115Speed;
		NULL_t	 uM116NULL;
		struct FANSICAOUnitNameFrequency	*uM117ICAOunitnameFrequency;
		struct FANSPositionICAOUnitNameFrequency	*uM118PositionICAOunitnameFrequency;
		struct FANSTimeICAOunitnameFrequency	*uM119TimeICAOunitnameFrequency;
		struct FANSICAOUnitNameFrequency	*uM120ICAOunitnameFrequency;
		struct FANSPositionICAOUnitNameFrequency	*uM121PositionICAOunitnameFrequency;
		struct FANSTimeICAOunitnameFrequency	*uM122TimeICAOunitnameFrequency;
		struct FANSBeaconCode	*uM123BeaconCode;
		NULL_t	 uM124NULL;
		NULL_t	 uM125NULL;
		NULL_t	 uM126NULL;
		NULL_t	 uM127NULL;
		struct FANSAltitude	*uM128Altitude;
		struct FANSAltitude	*uM129Altitude;
		struct FANSPosition	*uM130Position;
		NULL_t	 uM131NULL;
		NULL_t	 uM132NULL;
		NULL_t	 uM133NULL;
		NULL_t	 uM134NULL;
		NULL_t	 uM135NULL;
		NULL_t	 uM136NULL;
		NULL_t	 uM137NULL;
		NULL_t	 uM138NULL;
		NULL_t	 uM139NULL;
		NULL_t	 uM140NULL;
		NULL_t	 uM141NULL;
		NULL_t	 uM142NULL;
		NULL_t	 uM143NULL;
		NULL_t	 uM144NULL;
		NULL_t	 uM145NULL;
		NULL_t	 uM146NULL;
		NULL_t	 uM147NULL;
		struct FANSAltitude	*uM148Altitude;
		struct FANSAltitudePosition	*uM149AltitudePosition;
		struct FANSAltitudeTime	*uM150AltitudeTime;
		struct FANSSpeed	*uM151Speed;
		struct FANSDistanceOffsetDirection	*uM152DistanceOffsetDirection;
		struct FANSAltimeter	*uM153Altimeter;
		NULL_t	 uM154NULL;
		struct FANSPosition	*uM155Position;
		NULL_t	 uM156NULL;
		struct FANSFrequency	*uM157Frequency;
		FANSATISCode_t	 uM158ATISCode;
		FANSErrorInformation_t	 uM159ErrorInformation;
		FANSICAOfacilityDesignation_t	 uM160ICAOfacilitydesignation;
		NULL_t	 uM161NULL;
		NULL_t	 uM162NULL;
		struct FANSICAOFacilityDesignationTp4Table	*uM163ICAOfacilitydesignationTp4table;
		NULL_t	 uM164NULL;
		NULL_t	 uM165NULL;
		NULL_t	 uM166NULL;
		NULL_t	 uM167NULL;
		NULL_t	 uM168NULL;
		FANSFreeText_t	 uM169FreeText;
		FANSFreeText_t	 uM170FreeText;
		struct FANSVerticalRate	*uM171VerticalRate;
		struct FANSVerticalRate	*uM172VerticalRate;
		struct FANSVerticalRate	*uM173VerticalRate;
		struct FANSVerticalRate	*uM174VerticalRate;
		struct FANSAltitude	*uM175Altitude;
		NULL_t	 uM176NULL;
		NULL_t	 uM177NULL;
		NULL_t	 uM178NULL;
		NULL_t	 uM179NULL;
		struct FANSAltitudeAltitude	*uM180AltitudeAltitude;
		struct FANSToFromPosition	*uM181ToFromPosition;
		NULL_t	 uM182NULL;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSATCUplinkMsgElementId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSATCUplinkMsgElementId;
extern asn_CHOICE_specifics_t asn_SPC_FANSATCUplinkMsgElementId_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSATCUplinkMsgElementId_1[183];
extern asn_per_constraints_t asn_PER_type_FANSATCUplinkMsgElementId_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSATCUplinkMsgElementId_H_ */
#include <asn_internal.h>
