/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSCOMNAVEquipmentStatus.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_FANSCOMNAVEquipmentStatus_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_FANSCOMNAVEquipmentStatus_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_FANSCOMNAVEquipmentStatus_value2enum_1[] = {
	{ 0,	7,	"aloranA" },
	{ 1,	7,	"cloranC" },
	{ 2,	4,	"ddme" },
	{ 3,	6,	"edecca" },
	{ 4,	4,	"fadf" },
	{ 5,	5,	"ggnss" },
	{ 6,	6,	"hhfRTF" },
	{ 7,	19,	"iinertialNavigation" },
	{ 8,	4,	"lils" },
	{ 9,	6,	"momega" },
	{ 10,	4,	"ovor" },
	{ 11,	8,	"pdoppler" },
	{ 12,	19,	"rrnavRouteEquipment" },
	{ 13,	6,	"ttacan" },
	{ 14,	7,	"uuhfRTF" },
	{ 15,	7,	"vvhfRTF" }
};
static const unsigned int asn_MAP_FANSCOMNAVEquipmentStatus_enum2value_1[] = {
	0,	/* aloranA(0) */
	1,	/* cloranC(1) */
	2,	/* ddme(2) */
	3,	/* edecca(3) */
	4,	/* fadf(4) */
	5,	/* ggnss(5) */
	6,	/* hhfRTF(6) */
	7,	/* iinertialNavigation(7) */
	8,	/* lils(8) */
	9,	/* momega(9) */
	10,	/* ovor(10) */
	11,	/* pdoppler(11) */
	12,	/* rrnavRouteEquipment(12) */
	13,	/* ttacan(13) */
	14,	/* uuhfRTF(14) */
	15	/* vvhfRTF(15) */
};
const asn_INTEGER_specifics_t asn_SPC_FANSCOMNAVEquipmentStatus_specs_1 = {
	asn_MAP_FANSCOMNAVEquipmentStatus_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_FANSCOMNAVEquipmentStatus_enum2value_1,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_FANSCOMNAVEquipmentStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FANSCOMNAVEquipmentStatus = {
	"FANSCOMNAVEquipmentStatus",
	"FANSCOMNAVEquipmentStatus",
	&asn_OP_NativeEnumerated,
	asn_DEF_FANSCOMNAVEquipmentStatus_tags_1,
	sizeof(asn_DEF_FANSCOMNAVEquipmentStatus_tags_1)
		/sizeof(asn_DEF_FANSCOMNAVEquipmentStatus_tags_1[0]), /* 1 */
	asn_DEF_FANSCOMNAVEquipmentStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSCOMNAVEquipmentStatus_tags_1)
		/sizeof(asn_DEF_FANSCOMNAVEquipmentStatus_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_FANSCOMNAVEquipmentStatus_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_FANSCOMNAVEquipmentStatus_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_FANSCOMNAVEquipmentStatus_specs_1	/* Additional specs */
};

