/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSProcedureName_H_
#define	_FANSProcedureName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSProcedureType.h"
#include "FANSProcedure.h"
#include "FANSProcedureTransition.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSProcedureName */
typedef struct FANSProcedureName {
	FANSProcedureType_t	 procedureType;
	FANSProcedure_t	 procedure;
	FANSProcedureTransition_t	*procedureTransition;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSProcedureName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedureName;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSProcedureName_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSProcedureName_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedureName_H_ */
#include "asn_internal.h"
