/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSAltimeter_H_
#define	_FANSAltimeter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSAltimeterEnglish.h"
#include "FANSAltimeterMetric.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSAltimeter_PR {
	FANSAltimeter_PR_NOTHING,	/* No components present */
	FANSAltimeter_PR_altimeterEnglish,
	FANSAltimeter_PR_altimeterMetric
} FANSAltimeter_PR;

/* FANSAltimeter */
typedef struct FANSAltimeter {
	FANSAltimeter_PR present;
	union FANSAltimeter_u {
		FANSAltimeterEnglish_t	 altimeterEnglish;
		FANSAltimeterMetric_t	 altimeterMetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSAltimeter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAltimeter;
extern asn_CHOICE_specifics_t asn_SPC_FANSAltimeter_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSAltimeter_1[2];
extern asn_per_constraints_t asn_PER_type_FANSAltimeter_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltimeter_H_ */
#include <asn_internal.h>
