/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSRouteInformationAdditional_H_
#define	_FANSRouteInformationAdditional_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSATWAlongTrackWaypointSequence;
struct FANSReportingPoints;
struct FANSInterceptCourseFromSequence;
struct FANSHoldatwaypointSequence;
struct FANSWaypointSpeedAltitudesequence;
struct FANSRTARequiredTimeArrivalSequence;

/* FANSRouteInformationAdditional */
typedef struct FANSRouteInformationAdditional {
	struct FANSATWAlongTrackWaypointSequence	*aTWalongtrackwaypointsequence;	/* OPTIONAL */
	struct FANSReportingPoints	*reportingPoints;	/* OPTIONAL */
	struct FANSInterceptCourseFromSequence	*interceptCourseFromSequence;	/* OPTIONAL */
	struct FANSHoldatwaypointSequence	*holdAtWaypointSequence;	/* OPTIONAL */
	struct FANSWaypointSpeedAltitudesequence	*waypointSpeedAltitudeSequence;	/* OPTIONAL */
	struct FANSRTARequiredTimeArrivalSequence	*rTArequiredtimearrivalsequenc;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRouteInformationAdditional_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRouteInformationAdditional;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSRouteInformationAdditional_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSRouteInformationAdditional_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSATWAlongTrackWaypointSequence.h"
#include "FANSReportingPoints.h"
#include "FANSInterceptCourseFromSequence.h"
#include "FANSHoldatwaypointSequence.h"
#include "FANSWaypointSpeedAltitudesequence.h"
#include "FANSRTARequiredTimeArrivalSequence.h"

#endif	/* _FANSRouteInformationAdditional_H_ */
#include "asn_internal.h"
