/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSPositionAltitudeSpeed_H_
#define	_FANSPositionAltitudeSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSAltitude.h"
#include "FANSSpeed.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPositionAltitudeSpeed */
typedef struct FANSPositionAltitudeSpeed {
	FANSPosition_t	 position;
	FANSAltitude_t	 altitude;
	FANSSpeed_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPositionAltitudeSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionAltitudeSpeed;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSPositionAltitudeSpeed_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSPositionAltitudeSpeed_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPositionAltitudeSpeed_H_ */
#include "asn_internal.h"
