/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSAirportDeparture_H_
#define	_FANSAirportDeparture_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSAirport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAirportDeparture */
typedef FANSAirport_t	 FANSAirportDeparture_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSAirportDeparture_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSAirportDeparture;
asn_struct_free_f FANSAirportDeparture_free;
asn_struct_print_f FANSAirportDeparture_print;
asn_constr_check_f FANSAirportDeparture_constraint;
ber_type_decoder_f FANSAirportDeparture_decode_ber;
der_type_encoder_f FANSAirportDeparture_encode_der;
xer_type_decoder_f FANSAirportDeparture_decode_xer;
xer_type_encoder_f FANSAirportDeparture_encode_xer;
jer_type_encoder_f FANSAirportDeparture_encode_jer;
oer_type_decoder_f FANSAirportDeparture_decode_oer;
oer_type_encoder_f FANSAirportDeparture_encode_oer;
per_type_decoder_f FANSAirportDeparture_decode_uper;
per_type_encoder_f FANSAirportDeparture_encode_uper;
per_type_decoder_f FANSAirportDeparture_decode_aper;
per_type_encoder_f FANSAirportDeparture_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAirportDeparture_H_ */
#include "asn_internal.h"
