/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSICAOFacilityDesignationTp4Table.h"

asn_TYPE_member_t asn_MBR_FANSICAOFacilityDesignationTp4Table_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSICAOFacilityDesignationTp4Table, iCAOFacilityDesignation),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_FANSICAOfacilityDesignation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iCAOFacilityDesignation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSICAOFacilityDesignationTp4Table, tp4table),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_FANSTp4table,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tp4table"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSICAOFacilityDesignationTp4Table_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 1, 0, 0 }, /* tp4table */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* iCAOFacilityDesignation */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSICAOFacilityDesignationTp4Table_specs_1 = {
	sizeof(struct FANSICAOFacilityDesignationTp4Table),
	offsetof(struct FANSICAOFacilityDesignationTp4Table, _asn_ctx),
	asn_MAP_FANSICAOFacilityDesignationTp4Table_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSICAOFacilityDesignationTp4Table = {
	"FANSICAOFacilityDesignationTp4Table",
	"FANSICAOFacilityDesignationTp4Table",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1,
	sizeof(asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1)
		/sizeof(asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1[0]), /* 1 */
	asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1)
		/sizeof(asn_DEF_FANSICAOFacilityDesignationTp4Table_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSICAOFacilityDesignationTp4Table_1,
	2,	/* Elements count */
	&asn_SPC_FANSICAOFacilityDesignationTp4Table_specs_1	/* Additional specs */
};

