/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSVerticalDirection_H_
#define	_FANSVerticalDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSVerticalDirection {
	FANSVerticalDirection_up	= 0,
	FANSVerticalDirection_down	= 1
} e_FANSVerticalDirection;

/* FANSVerticalDirection */
typedef long	 FANSVerticalDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSVerticalDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSVerticalDirection;
extern const asn_INTEGER_specifics_t asn_SPC_FANSVerticalDirection_specs_1;
asn_struct_free_f FANSVerticalDirection_free;
asn_struct_print_f FANSVerticalDirection_print;
asn_constr_check_f FANSVerticalDirection_constraint;
ber_type_decoder_f FANSVerticalDirection_decode_ber;
der_type_encoder_f FANSVerticalDirection_encode_der;
xer_type_decoder_f FANSVerticalDirection_decode_xer;
xer_type_encoder_f FANSVerticalDirection_encode_xer;
jer_type_encoder_f FANSVerticalDirection_encode_jer;
oer_type_decoder_f FANSVerticalDirection_decode_oer;
oer_type_encoder_f FANSVerticalDirection_encode_oer;
per_type_decoder_f FANSVerticalDirection_decode_uper;
per_type_encoder_f FANSVerticalDirection_encode_uper;
per_type_decoder_f FANSVerticalDirection_decode_aper;
per_type_encoder_f FANSVerticalDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSVerticalDirection_H_ */
#include "asn_internal.h"
