/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSDegrees_H_
#define	_FANSDegrees_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSDegreesMagnetic.h"
#include "FANSDegreesTrue.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSDegrees_PR {
	FANSDegrees_PR_NOTHING,	/* No components present */
	FANSDegrees_PR_degreesMagnetic,
	FANSDegrees_PR_degreesTrue
} FANSDegrees_PR;

/* FANSDegrees */
typedef struct FANSDegrees {
	FANSDegrees_PR present;
	union FANSDegrees_u {
		FANSDegreesMagnetic_t	 degreesMagnetic;
		FANSDegreesTrue_t	 degreesTrue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSDegrees_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSDegrees;
extern asn_CHOICE_specifics_t asn_SPC_FANSDegrees_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSDegrees_1[2];
extern asn_per_constraints_t asn_PER_type_FANSDegrees_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSDegrees_H_ */
#include "asn_internal.h"
