/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSLongitudeDegrees_H_
#define	_FANSLongitudeDegrees_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FANSLongitudeDegrees */
typedef long	 FANSLongitudeDegrees_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSLongitudeDegrees_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSLongitudeDegrees;
asn_struct_free_f FANSLongitudeDegrees_free;
asn_struct_print_f FANSLongitudeDegrees_print;
asn_constr_check_f FANSLongitudeDegrees_constraint;
ber_type_decoder_f FANSLongitudeDegrees_decode_ber;
der_type_encoder_f FANSLongitudeDegrees_encode_der;
xer_type_decoder_f FANSLongitudeDegrees_decode_xer;
xer_type_encoder_f FANSLongitudeDegrees_encode_xer;
jer_type_encoder_f FANSLongitudeDegrees_encode_jer;
oer_type_decoder_f FANSLongitudeDegrees_decode_oer;
oer_type_encoder_f FANSLongitudeDegrees_encode_oer;
per_type_decoder_f FANSLongitudeDegrees_decode_uper;
per_type_encoder_f FANSLongitudeDegrees_encode_uper;
per_type_decoder_f FANSLongitudeDegrees_decode_aper;
per_type_encoder_f FANSLongitudeDegrees_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSLongitudeDegrees_H_ */
#include <asn_internal.h>
