/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSLongitudeReportingPoints.h"

asn_TYPE_member_t asn_MBR_FANSLongitudeReportingPoints_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSLongitudeReportingPoints, longitudeDirection),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_FANSLongitudeDirection,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"longitudeDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSLongitudeReportingPoints, longitudeDegrees),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_FANSLongitudeDegrees,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"longitudeDegrees"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSLongitudeReportingPoints_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSLongitudeReportingPoints_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* longitudeDegrees */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 0, 0, 0 } /* longitudeDirection */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSLongitudeReportingPoints_specs_1 = {
	sizeof(struct FANSLongitudeReportingPoints),
	offsetof(struct FANSLongitudeReportingPoints, _asn_ctx),
	asn_MAP_FANSLongitudeReportingPoints_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSLongitudeReportingPoints = {
	"FANSLongitudeReportingPoints",
	"FANSLongitudeReportingPoints",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSLongitudeReportingPoints_tags_1,
	sizeof(asn_DEF_FANSLongitudeReportingPoints_tags_1)
		/sizeof(asn_DEF_FANSLongitudeReportingPoints_tags_1[0]), /* 1 */
	asn_DEF_FANSLongitudeReportingPoints_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSLongitudeReportingPoints_tags_1)
		/sizeof(asn_DEF_FANSLongitudeReportingPoints_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSLongitudeReportingPoints_1,
	2,	/* Elements count */
	&asn_SPC_FANSLongitudeReportingPoints_specs_1	/* Additional specs */
};

