/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSATWDistanceTolerance_H_
#define	_FANSATWDistanceTolerance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSATWDistanceTolerance {
	FANSATWDistanceTolerance_plus	= 0,
	FANSATWDistanceTolerance_minus	= 1
} e_FANSATWDistanceTolerance;

/* FANSATWDistanceTolerance */
typedef long	 FANSATWDistanceTolerance_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSATWDistanceTolerance_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSATWDistanceTolerance;
extern const asn_INTEGER_specifics_t asn_SPC_FANSATWDistanceTolerance_specs_1;
asn_struct_free_f FANSATWDistanceTolerance_free;
asn_struct_print_f FANSATWDistanceTolerance_print;
asn_constr_check_f FANSATWDistanceTolerance_constraint;
ber_type_decoder_f FANSATWDistanceTolerance_decode_ber;
der_type_encoder_f FANSATWDistanceTolerance_encode_der;
xer_type_decoder_f FANSATWDistanceTolerance_decode_xer;
xer_type_encoder_f FANSATWDistanceTolerance_encode_xer;
jer_type_encoder_f FANSATWDistanceTolerance_encode_jer;
oer_type_decoder_f FANSATWDistanceTolerance_decode_oer;
oer_type_encoder_f FANSATWDistanceTolerance_encode_oer;
per_type_decoder_f FANSATWDistanceTolerance_decode_uper;
per_type_encoder_f FANSATWDistanceTolerance_encode_uper;
per_type_decoder_f FANSATWDistanceTolerance_decode_aper;
per_type_encoder_f FANSATWDistanceTolerance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSATWDistanceTolerance_H_ */
#include "asn_internal.h"
