/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSPosition_H_
#define	_FANSPosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSFixName.h"
#include "FANSNavaid.h"
#include "FANSAirport.h"
#include "FANSLatitudeLongitude.h"
#include "FANSPlaceBearingDistance.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSPosition_PR {
	FANSPosition_PR_NOTHING,	/* No components present */
	FANSPosition_PR_fixName,
	FANSPosition_PR_navaid,
	FANSPosition_PR_airport,
	FANSPosition_PR_latitudeLongitude,
	FANSPosition_PR_placeBearingDistance
} FANSPosition_PR;

/* FANSPosition */
typedef struct FANSPosition {
	FANSPosition_PR present;
	union FANSPosition_u {
		FANSFixName_t	 fixName;
		FANSNavaid_t	 navaid;
		FANSAirport_t	 airport;
		FANSLatitudeLongitude_t	 latitudeLongitude;
		FANSPlaceBearingDistance_t	 placeBearingDistance;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPosition;
extern asn_CHOICE_specifics_t asn_SPC_FANSPosition_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSPosition_1[5];
extern asn_per_constraints_t asn_PER_type_FANSPosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPosition_H_ */
#include "asn_internal.h"
