/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSATWAltitudeTolerance_H_
#define	_FANSATWAltitudeTolerance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSATWAltitudeTolerance {
	FANSATWAltitudeTolerance_at	= 0,
	FANSATWAltitudeTolerance_atorabove	= 1,
	FANSATWAltitudeTolerance_atorbelow	= 2
} e_FANSATWAltitudeTolerance;

/* FANSATWAltitudeTolerance */
typedef long	 FANSATWAltitudeTolerance_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSATWAltitudeTolerance_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSATWAltitudeTolerance;
extern const asn_INTEGER_specifics_t asn_SPC_FANSATWAltitudeTolerance_specs_1;
asn_struct_free_f FANSATWAltitudeTolerance_free;
asn_struct_print_f FANSATWAltitudeTolerance_print;
asn_constr_check_f FANSATWAltitudeTolerance_constraint;
ber_type_decoder_f FANSATWAltitudeTolerance_decode_ber;
der_type_encoder_f FANSATWAltitudeTolerance_encode_der;
xer_type_decoder_f FANSATWAltitudeTolerance_decode_xer;
xer_type_encoder_f FANSATWAltitudeTolerance_encode_xer;
jer_type_encoder_f FANSATWAltitudeTolerance_encode_jer;
oer_type_decoder_f FANSATWAltitudeTolerance_decode_oer;
oer_type_encoder_f FANSATWAltitudeTolerance_encode_oer;
per_type_decoder_f FANSATWAltitudeTolerance_decode_uper;
per_type_encoder_f FANSATWAltitudeTolerance_encode_uper;
per_type_decoder_f FANSATWAltitudeTolerance_decode_aper;
per_type_encoder_f FANSATWAltitudeTolerance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSATWAltitudeTolerance_H_ */
#include <asn_internal.h>
