/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSErrorInformation.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_FANSErrorInformation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_FANSErrorInformation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_FANSErrorInformation_value2enum_1[] = {
	{ 0,	16,	"applicationError" },
	{ 1,	32,	"duplicateMsgIdentificationNumber" },
	{ 2,	30,	"unrecognizedMsgReferenceNumber" },
	{ 3,	25,	"endServiceWithPendingMsgs" },
	{ 4,	29,	"endServiceWithNoValidResponse" },
	{ 5,	30,	"insufficientMsgStorageCapacity" },
	{ 6,	34,	"noAvailableMsgIdentificationNumber" },
	{ 7,	20,	"commandedTermination" },
	{ 8,	16,	"insufficientData" },
	{ 9,	14,	"unexpectedData" },
	{ 10,	11,	"invalidData" },
	{ 16,	16,	"reservedErrorMsg" }
};
static const unsigned int asn_MAP_FANSErrorInformation_enum2value_1[] = {
	0,	/* applicationError(0) */
	7,	/* commandedTermination(7) */
	1,	/* duplicateMsgIdentificationNumber(1) */
	4,	/* endServiceWithNoValidResponse(4) */
	3,	/* endServiceWithPendingMsgs(3) */
	8,	/* insufficientData(8) */
	5,	/* insufficientMsgStorageCapacity(5) */
	10,	/* invalidData(10) */
	6,	/* noAvailableMsgIdentificationNumber(6) */
	11,	/* reservedErrorMsg(16) */
	9,	/* unexpectedData(9) */
	2	/* unrecognizedMsgReferenceNumber(2) */
};
const asn_INTEGER_specifics_t asn_SPC_FANSErrorInformation_specs_1 = {
	asn_MAP_FANSErrorInformation_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_FANSErrorInformation_enum2value_1,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_FANSErrorInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FANSErrorInformation = {
	"FANSErrorInformation",
	"FANSErrorInformation",
	&asn_OP_NativeEnumerated,
	asn_DEF_FANSErrorInformation_tags_1,
	sizeof(asn_DEF_FANSErrorInformation_tags_1)
		/sizeof(asn_DEF_FANSErrorInformation_tags_1[0]), /* 1 */
	asn_DEF_FANSErrorInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSErrorInformation_tags_1)
		/sizeof(asn_DEF_FANSErrorInformation_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_FANSErrorInformation_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_FANSErrorInformation_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_FANSErrorInformation_specs_1	/* Additional specs */
};

