/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSDirection.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_FANSDirection_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_FANSDirection_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (0..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_FANSDirection_value2enum_1[] = {
	{ 0,	4,	"left" },
	{ 1,	5,	"right" },
	{ 2,	10,	"eitherSide" },
	{ 3,	5,	"north" },
	{ 4,	5,	"south" },
	{ 5,	4,	"east" },
	{ 6,	4,	"west" },
	{ 7,	9,	"northEast" },
	{ 8,	9,	"northWest" },
	{ 9,	9,	"southEast" },
	{ 10,	9,	"southWest" }
};
static const unsigned int asn_MAP_FANSDirection_enum2value_1[] = {
	5,	/* east(5) */
	2,	/* eitherSide(2) */
	0,	/* left(0) */
	3,	/* north(3) */
	7,	/* northEast(7) */
	8,	/* northWest(8) */
	1,	/* right(1) */
	4,	/* south(4) */
	9,	/* southEast(9) */
	10,	/* southWest(10) */
	6	/* west(6) */
};
const asn_INTEGER_specifics_t asn_SPC_FANSDirection_specs_1 = {
	asn_MAP_FANSDirection_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_FANSDirection_enum2value_1,	/* N => "tag"; sorted by N */
	11,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_FANSDirection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FANSDirection = {
	"FANSDirection",
	"FANSDirection",
	&asn_OP_NativeEnumerated,
	asn_DEF_FANSDirection_tags_1,
	sizeof(asn_DEF_FANSDirection_tags_1)
		/sizeof(asn_DEF_FANSDirection_tags_1[0]), /* 1 */
	asn_DEF_FANSDirection_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSDirection_tags_1)
		/sizeof(asn_DEF_FANSDirection_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_FANSDirection_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_FANSDirection_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_FANSDirection_specs_1	/* Additional specs */
};

