/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSProcedureApproach_H_
#define	_FANSProcedureApproach_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSProcedureName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSProcedureApproach */
typedef FANSProcedureName_t	 FANSProcedureApproach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedureApproach;
asn_struct_free_f FANSProcedureApproach_free;
asn_struct_print_f FANSProcedureApproach_print;
asn_constr_check_f FANSProcedureApproach_constraint;
ber_type_decoder_f FANSProcedureApproach_decode_ber;
der_type_encoder_f FANSProcedureApproach_encode_der;
xer_type_decoder_f FANSProcedureApproach_decode_xer;
xer_type_encoder_f FANSProcedureApproach_encode_xer;
jer_type_encoder_f FANSProcedureApproach_encode_jer;
oer_type_decoder_f FANSProcedureApproach_decode_oer;
oer_type_encoder_f FANSProcedureApproach_encode_oer;
per_type_decoder_f FANSProcedureApproach_decode_uper;
per_type_encoder_f FANSProcedureApproach_encode_uper;
per_type_decoder_f FANSProcedureApproach_decode_aper;
per_type_encoder_f FANSProcedureApproach_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedureApproach_H_ */
#include "asn_internal.h"
