/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSErrorInformation_H_
#define	_FANSErrorInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSErrorInformation {
	FANSErrorInformation_applicationError	= 0,
	FANSErrorInformation_duplicateMsgIdentificationNumber	= 1,
	FANSErrorInformation_unrecognizedMsgReferenceNumber	= 2,
	FANSErrorInformation_endServiceWithPendingMsgs	= 3,
	FANSErrorInformation_endServiceWithNoValidResponse	= 4,
	FANSErrorInformation_insufficientMsgStorageCapacity	= 5,
	FANSErrorInformation_noAvailableMsgIdentificationNumber	= 6,
	FANSErrorInformation_commandedTermination	= 7,
	FANSErrorInformation_insufficientData	= 8,
	FANSErrorInformation_unexpectedData	= 9,
	FANSErrorInformation_invalidData	= 10,
	FANSErrorInformation_reservedErrorMsg	= 16
} e_FANSErrorInformation;

/* FANSErrorInformation */
typedef long	 FANSErrorInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSErrorInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSErrorInformation;
extern const asn_INTEGER_specifics_t asn_SPC_FANSErrorInformation_specs_1;
asn_struct_free_f FANSErrorInformation_free;
asn_struct_print_f FANSErrorInformation_print;
asn_constr_check_f FANSErrorInformation_constraint;
ber_type_decoder_f FANSErrorInformation_decode_ber;
der_type_encoder_f FANSErrorInformation_encode_der;
xer_type_decoder_f FANSErrorInformation_decode_xer;
xer_type_encoder_f FANSErrorInformation_encode_xer;
jer_type_encoder_f FANSErrorInformation_encode_jer;
oer_type_decoder_f FANSErrorInformation_decode_oer;
oer_type_encoder_f FANSErrorInformation_encode_oer;
per_type_decoder_f FANSErrorInformation_decode_uper;
per_type_encoder_f FANSErrorInformation_encode_uper;
per_type_decoder_f FANSErrorInformation_decode_aper;
per_type_encoder_f FANSErrorInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSErrorInformation_H_ */
#include "asn_internal.h"
