/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSATCMessageHeader_H_
#define	_FANSATCMessageHeader_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSMsgIdentificationNumber.h"
#include "FANSMsgReferenceNumber.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSTimestamp;

/* FANSATCMessageHeader */
typedef struct FANSATCMessageHeader {
	FANSMsgIdentificationNumber_t	 msgIdentificationNumber;
	FANSMsgReferenceNumber_t	*msgReferenceNumber;	/* OPTIONAL */
	struct FANSTimestamp	*timestamp;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSATCMessageHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSATCMessageHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSATCMessageHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSATCMessageHeader_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSTimestamp.h"

#endif	/* _FANSATCMessageHeader_H_ */
#include "asn_internal.h"
