/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSTimeEtaAtFixNext_H_
#define	_FANSTimeEtaAtFixNext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeEtaAtFixNext */
typedef FANSTime_t	 FANSTimeEtaAtFixNext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeEtaAtFixNext;
asn_struct_free_f FANSTimeEtaAtFixNext_free;
asn_struct_print_f FANSTimeEtaAtFixNext_print;
asn_constr_check_f FANSTimeEtaAtFixNext_constraint;
ber_type_decoder_f FANSTimeEtaAtFixNext_decode_ber;
der_type_encoder_f FANSTimeEtaAtFixNext_encode_der;
xer_type_decoder_f FANSTimeEtaAtFixNext_decode_xer;
xer_type_encoder_f FANSTimeEtaAtFixNext_encode_xer;
jer_type_encoder_f FANSTimeEtaAtFixNext_encode_jer;
oer_type_decoder_f FANSTimeEtaAtFixNext_decode_oer;
oer_type_encoder_f FANSTimeEtaAtFixNext_encode_oer;
per_type_decoder_f FANSTimeEtaAtFixNext_decode_uper;
per_type_encoder_f FANSTimeEtaAtFixNext_encode_uper;
per_type_decoder_f FANSTimeEtaAtFixNext_decode_aper;
per_type_encoder_f FANSTimeEtaAtFixNext_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeEtaAtFixNext_H_ */
#include <asn_internal.h>
