/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSLatitude_H_
#define	_FANSLatitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSLatitudeDegrees.h"
#include "FANSMinutesLatLon.h"
#include "FANSLatitudeDirection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSLatitude */
typedef struct FANSLatitude {
	FANSLatitudeDegrees_t	 latitudeDegrees;
	FANSMinutesLatLon_t	*minutesLatLon;	/* OPTIONAL */
	FANSLatitudeDirection_t	 latitudeDirection;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSLatitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSLatitude;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSLatitude_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSLatitude_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSLatitude_H_ */
#include "asn_internal.h"
