/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSPositionProcedureName_H_
#define	_FANSPositionProcedureName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSProcedureName.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPositionProcedureName */
typedef struct FANSPositionProcedureName {
	FANSPosition_t	 position;
	FANSProcedureName_t	 procedureName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPositionProcedureName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionProcedureName;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSPositionProcedureName_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSPositionProcedureName_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPositionProcedureName_H_ */
#include "asn_internal.h"
