/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSAltitudeQNH_H_
#define	_FANSAltitudeQNH_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltitudeQNH */
typedef long	 FANSAltitudeQNH_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSAltitudeQNH_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSAltitudeQNH;
asn_struct_free_f FANSAltitudeQNH_free;
asn_struct_print_f FANSAltitudeQNH_print;
asn_constr_check_f FANSAltitudeQNH_constraint;
ber_type_decoder_f FANSAltitudeQNH_decode_ber;
der_type_encoder_f FANSAltitudeQNH_encode_der;
xer_type_decoder_f FANSAltitudeQNH_decode_xer;
xer_type_encoder_f FANSAltitudeQNH_encode_xer;
jer_type_encoder_f FANSAltitudeQNH_encode_jer;
oer_type_decoder_f FANSAltitudeQNH_decode_oer;
oer_type_encoder_f FANSAltitudeQNH_encode_oer;
per_type_decoder_f FANSAltitudeQNH_decode_uper;
per_type_encoder_f FANSAltitudeQNH_encode_uper;
per_type_decoder_f FANSAltitudeQNH_decode_aper;
per_type_encoder_f FANSAltitudeQNH_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltitudeQNH_H_ */
#include "asn_internal.h"
