/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSICAOFacilityDesignationTp4Table_H_
#define	_FANSICAOFacilityDesignationTp4Table_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSICAOfacilityDesignation.h"
#include "FANSTp4table.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSICAOFacilityDesignationTp4Table */
typedef struct FANSICAOFacilityDesignationTp4Table {
	FANSICAOfacilityDesignation_t	 iCAOFacilityDesignation;
	FANSTp4table_t	 tp4table;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSICAOFacilityDesignationTp4Table_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSICAOFacilityDesignationTp4Table;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSICAOFacilityDesignationTp4Table_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSICAOFacilityDesignationTp4Table_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSICAOFacilityDesignationTp4Table_H_ */
#include "asn_internal.h"
