/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSCOMNAVApproachEquipmentAvailable_H_
#define	_FANSCOMNAVApproachEquipmentAvailable_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSCOMNAVApproachEquipmentAvailable */
typedef BOOLEAN_t	 FANSCOMNAVApproachEquipmentAvailable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSCOMNAVApproachEquipmentAvailable;
asn_struct_free_f FANSCOMNAVApproachEquipmentAvailable_free;
asn_struct_print_f FANSCOMNAVApproachEquipmentAvailable_print;
asn_constr_check_f FANSCOMNAVApproachEquipmentAvailable_constraint;
ber_type_decoder_f FANSCOMNAVApproachEquipmentAvailable_decode_ber;
der_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_der;
xer_type_decoder_f FANSCOMNAVApproachEquipmentAvailable_decode_xer;
xer_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_xer;
jer_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_jer;
oer_type_decoder_f FANSCOMNAVApproachEquipmentAvailable_decode_oer;
oer_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_oer;
per_type_decoder_f FANSCOMNAVApproachEquipmentAvailable_decode_uper;
per_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_uper;
per_type_decoder_f FANSCOMNAVApproachEquipmentAvailable_decode_aper;
per_type_encoder_f FANSCOMNAVApproachEquipmentAvailable_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSCOMNAVApproachEquipmentAvailable_H_ */
#include "asn_internal.h"
