/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSRouteInformation_H_
#define	_FANSRouteInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSAirwayIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSRouteInformation_PR {
	FANSRouteInformation_PR_NOTHING,	/* No components present */
	FANSRouteInformation_PR_publishedIdentifier,
	FANSRouteInformation_PR_latitudeLongitude,
	FANSRouteInformation_PR_placeBearingPlaceBearing,
	FANSRouteInformation_PR_placeBearingDistance,
	FANSRouteInformation_PR_airwayIdentifier,
	FANSRouteInformation_PR_trackDetail
} FANSRouteInformation_PR;

/* Forward declarations */
struct FANSPublishedIdentifier;
struct FANSLatitudeLongitude;
struct FANSPlaceBearingPlaceBearing;
struct FANSPlaceBearingDistance;
struct FANSTrackDetail;

/* FANSRouteInformation */
typedef struct FANSRouteInformation {
	FANSRouteInformation_PR present;
	union FANSRouteInformation_u {
		struct FANSPublishedIdentifier	*publishedIdentifier;
		struct FANSLatitudeLongitude	*latitudeLongitude;
		struct FANSPlaceBearingPlaceBearing	*placeBearingPlaceBearing;
		struct FANSPlaceBearingDistance	*placeBearingDistance;
		FANSAirwayIdentifier_t	 airwayIdentifier;
		struct FANSTrackDetail	*trackDetail;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRouteInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRouteInformation;
extern asn_CHOICE_specifics_t asn_SPC_FANSRouteInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSRouteInformation_1[6];
extern asn_per_constraints_t asn_PER_type_FANSRouteInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRouteInformation_H_ */
#include <asn_internal.h>
