/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSAirportDestination_H_
#define	_FANSAirportDestination_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSAirport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAirportDestination */
typedef FANSAirport_t	 FANSAirportDestination_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSAirportDestination_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSAirportDestination;
asn_struct_free_f FANSAirportDestination_free;
asn_struct_print_f FANSAirportDestination_print;
asn_constr_check_f FANSAirportDestination_constraint;
ber_type_decoder_f FANSAirportDestination_decode_ber;
der_type_encoder_f FANSAirportDestination_encode_der;
xer_type_decoder_f FANSAirportDestination_decode_xer;
xer_type_encoder_f FANSAirportDestination_encode_xer;
jer_type_encoder_f FANSAirportDestination_encode_jer;
oer_type_decoder_f FANSAirportDestination_decode_oer;
oer_type_encoder_f FANSAirportDestination_encode_oer;
per_type_decoder_f FANSAirportDestination_decode_uper;
per_type_encoder_f FANSAirportDestination_encode_uper;
per_type_decoder_f FANSAirportDestination_decode_aper;
per_type_encoder_f FANSAirportDestination_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAirportDestination_H_ */
#include "asn_internal.h"
