/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSVerticalRateEnglish_H_
#define	_FANSVerticalRateEnglish_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSVerticalRateEnglish */
typedef long	 FANSVerticalRateEnglish_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSVerticalRateEnglish_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSVerticalRateEnglish;
asn_struct_free_f FANSVerticalRateEnglish_free;
asn_struct_print_f FANSVerticalRateEnglish_print;
asn_constr_check_f FANSVerticalRateEnglish_constraint;
ber_type_decoder_f FANSVerticalRateEnglish_decode_ber;
der_type_encoder_f FANSVerticalRateEnglish_encode_der;
xer_type_decoder_f FANSVerticalRateEnglish_decode_xer;
xer_type_encoder_f FANSVerticalRateEnglish_encode_xer;
jer_type_encoder_f FANSVerticalRateEnglish_encode_jer;
oer_type_decoder_f FANSVerticalRateEnglish_decode_oer;
oer_type_encoder_f FANSVerticalRateEnglish_encode_oer;
per_type_decoder_f FANSVerticalRateEnglish_decode_uper;
per_type_encoder_f FANSVerticalRateEnglish_encode_uper;
per_type_decoder_f FANSVerticalRateEnglish_decode_aper;
per_type_encoder_f FANSVerticalRateEnglish_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSVerticalRateEnglish_H_ */
#include "asn_internal.h"
