/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSTrackDetail.h"

asn_TYPE_member_t asn_MBR_FANSTrackDetail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, trackName),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_FANSTrackName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"trackName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, latitudeLongitude_seqOf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSLatitudeLongitudeSequence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"latitudeLongitude-seqOf"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSTrackDetail_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSTrackDetail_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* latitudeLongitude-seqOf */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* trackName */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSTrackDetail_specs_1 = {
	sizeof(struct FANSTrackDetail),
	offsetof(struct FANSTrackDetail, _asn_ctx),
	asn_MAP_FANSTrackDetail_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSTrackDetail = {
	"FANSTrackDetail",
	"FANSTrackDetail",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSTrackDetail_tags_1,
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	asn_DEF_FANSTrackDetail_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSTrackDetail_1,
	2,	/* Elements count */
	&asn_SPC_FANSTrackDetail_specs_1	/* Additional specs */
};

