/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSAltimeterEnglish_H_
#define	_FANSAltimeterEnglish_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltimeterEnglish */
typedef long	 FANSAltimeterEnglish_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSAltimeterEnglish_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSAltimeterEnglish;
asn_struct_free_f FANSAltimeterEnglish_free;
asn_struct_print_f FANSAltimeterEnglish_print;
asn_constr_check_f FANSAltimeterEnglish_constraint;
ber_type_decoder_f FANSAltimeterEnglish_decode_ber;
der_type_encoder_f FANSAltimeterEnglish_encode_der;
xer_type_decoder_f FANSAltimeterEnglish_decode_xer;
xer_type_encoder_f FANSAltimeterEnglish_encode_xer;
jer_type_encoder_f FANSAltimeterEnglish_encode_jer;
oer_type_decoder_f FANSAltimeterEnglish_decode_oer;
oer_type_encoder_f FANSAltimeterEnglish_encode_oer;
per_type_decoder_f FANSAltimeterEnglish_decode_uper;
per_type_encoder_f FANSAltimeterEnglish_encode_uper;
per_type_decoder_f FANSAltimeterEnglish_decode_aper;
per_type_encoder_f FANSAltimeterEnglish_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltimeterEnglish_H_ */
#include "asn_internal.h"
