/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSRouteClearance_H_
#define	_FANSRouteClearance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSAirportDeparture.h"
#include "FANSAirportDestination.h"
#include "FANSAirwayIntercept.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSRunwayDeparture;
struct FANSProcedureDeparture;
struct FANSRunwayArrival;
struct FANSProcedureApproach;
struct FANSProcedureArrival;
struct FANSRouteInformationSequence;
struct FANSRouteInformationAdditional;

/* FANSRouteClearance */
typedef struct FANSRouteClearance {
	FANSAirportDeparture_t	*airportDeparture;	/* OPTIONAL */
	FANSAirportDestination_t	*airportDestination;	/* OPTIONAL */
	struct FANSRunwayDeparture	*runwayDeparture;	/* OPTIONAL */
	struct FANSProcedureDeparture	*procedureDeparture;	/* OPTIONAL */
	struct FANSRunwayArrival	*runwayArrival;	/* OPTIONAL */
	struct FANSProcedureApproach	*procedureApproach;	/* OPTIONAL */
	struct FANSProcedureArrival	*procedureArrival;	/* OPTIONAL */
	FANSAirwayIntercept_t	*airwayIntercept;	/* OPTIONAL */
	struct FANSRouteInformationSequence	*routeinformation_seqOf;	/* OPTIONAL */
	struct FANSRouteInformationAdditional	*routeInformationAdditional;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRouteClearance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRouteClearance;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSRouteClearance_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSRouteClearance_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSRunwayDeparture.h"
#include "FANSProcedureDeparture.h"
#include "FANSRunwayArrival.h"
#include "FANSProcedureApproach.h"
#include "FANSProcedureArrival.h"
#include "FANSRouteInformationSequence.h"
#include "FANSRouteInformationAdditional.h"

#endif	/* _FANSRouteClearance_H_ */
#include "asn_internal.h"
