/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSSSREquipmentAvailable.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_FANSSSREquipmentAvailable_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_FANSSSREquipmentAvailable_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_FANSSSREquipmentAvailable_value2enum_1[] = {
	{ 0,	4,	"nnil" },
	{ 1,	17,	"atransponderModeA" },
	{ 2,	21,	"ctransponderModeAandC" },
	{ 3,	17,	"xtransponderModeS" },
	{ 4,	19,	"ptransponderModeSPA" },
	{ 5,	19,	"itransponderModeSID" },
	{ 6,	21,	"stransponderModeSPAID" }
};
static const unsigned int asn_MAP_FANSSSREquipmentAvailable_enum2value_1[] = {
	1,	/* atransponderModeA(1) */
	2,	/* ctransponderModeAandC(2) */
	5,	/* itransponderModeSID(5) */
	0,	/* nnil(0) */
	4,	/* ptransponderModeSPA(4) */
	6,	/* stransponderModeSPAID(6) */
	3	/* xtransponderModeS(3) */
};
const asn_INTEGER_specifics_t asn_SPC_FANSSSREquipmentAvailable_specs_1 = {
	asn_MAP_FANSSSREquipmentAvailable_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_FANSSSREquipmentAvailable_enum2value_1,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_FANSSSREquipmentAvailable_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FANSSSREquipmentAvailable = {
	"FANSSSREquipmentAvailable",
	"FANSSSREquipmentAvailable",
	&asn_OP_NativeEnumerated,
	asn_DEF_FANSSSREquipmentAvailable_tags_1,
	sizeof(asn_DEF_FANSSSREquipmentAvailable_tags_1)
		/sizeof(asn_DEF_FANSSSREquipmentAvailable_tags_1[0]), /* 1 */
	asn_DEF_FANSSSREquipmentAvailable_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSSSREquipmentAvailable_tags_1)
		/sizeof(asn_DEF_FANSSSREquipmentAvailable_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_FANSSSREquipmentAvailable_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_FANSSSREquipmentAvailable_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_FANSSSREquipmentAvailable_specs_1	/* Additional specs */
};

