/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSHoldatwaypoint_H_
#define	_FANSHoldatwaypoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSDirection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSHoldatwaypointSpeedLow;
struct FANSATWAltitude;
struct FANSHoldatwaypointSpeedHigh;
struct FANSDegrees;
struct FANSEFCtime;
struct FANSLegType;

/* FANSHoldatwaypoint */
typedef struct FANSHoldatwaypoint {
	FANSPosition_t	 position;
	struct FANSHoldatwaypointSpeedLow	*holdatwaypointspeedlow;	/* OPTIONAL */
	struct FANSATWAltitude	*aTWaltitude;	/* OPTIONAL */
	struct FANSHoldatwaypointSpeedHigh	*holdatwaypointspeedhigh;	/* OPTIONAL */
	FANSDirection_t	*direction;	/* OPTIONAL */
	struct FANSDegrees	*degrees;	/* OPTIONAL */
	struct FANSEFCtime	*eFCtime;	/* OPTIONAL */
	struct FANSLegType	*legType;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSHoldatwaypoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSHoldatwaypoint;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSHoldatwaypoint_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSHoldatwaypoint_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSHoldatwaypointSpeedLow.h"
#include "FANSATWAltitude.h"
#include "FANSHoldatwaypointSpeedHigh.h"
#include "FANSDegrees.h"
#include "FANSEFCtime.h"
#include "FANSLegType.h"

#endif	/* _FANSHoldatwaypoint_H_ */
#include "asn_internal.h"
