/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSProcedureArrival_H_
#define	_FANSProcedureArrival_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSProcedureName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSProcedureArrival */
typedef FANSProcedureName_t	 FANSProcedureArrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedureArrival;
asn_struct_free_f FANSProcedureArrival_free;
asn_struct_print_f FANSProcedureArrival_print;
asn_constr_check_f FANSProcedureArrival_constraint;
ber_type_decoder_f FANSProcedureArrival_decode_ber;
der_type_encoder_f FANSProcedureArrival_encode_der;
xer_type_decoder_f FANSProcedureArrival_decode_xer;
xer_type_encoder_f FANSProcedureArrival_encode_xer;
jer_type_encoder_f FANSProcedureArrival_encode_jer;
oer_type_decoder_f FANSProcedureArrival_decode_oer;
oer_type_encoder_f FANSProcedureArrival_encode_oer;
per_type_decoder_f FANSProcedureArrival_decode_uper;
per_type_encoder_f FANSProcedureArrival_encode_uper;
per_type_decoder_f FANSProcedureArrival_decode_aper;
per_type_encoder_f FANSProcedureArrival_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedureArrival_H_ */
#include <asn_internal.h>
