/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSPDCrevision_H_
#define	_FANSPDCrevision_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPDCrevision */
typedef long	 FANSPDCrevision_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSPDCrevision_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSPDCrevision;
asn_struct_free_f FANSPDCrevision_free;
asn_struct_print_f FANSPDCrevision_print;
asn_constr_check_f FANSPDCrevision_constraint;
ber_type_decoder_f FANSPDCrevision_decode_ber;
der_type_encoder_f FANSPDCrevision_encode_der;
xer_type_decoder_f FANSPDCrevision_decode_xer;
xer_type_encoder_f FANSPDCrevision_encode_xer;
jer_type_encoder_f FANSPDCrevision_encode_jer;
oer_type_decoder_f FANSPDCrevision_decode_oer;
oer_type_encoder_f FANSPDCrevision_encode_oer;
per_type_decoder_f FANSPDCrevision_decode_uper;
per_type_encoder_f FANSPDCrevision_encode_uper;
per_type_decoder_f FANSPDCrevision_decode_aper;
per_type_encoder_f FANSPDCrevision_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPDCrevision_H_ */
#include <asn_internal.h>
