/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSToFrom_H_
#define	_FANSToFrom_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSToFrom {
	FANSToFrom_to	= 0,
	FANSToFrom_from	= 1
} e_FANSToFrom;

/* FANSToFrom */
typedef long	 FANSToFrom_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSToFrom_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSToFrom;
extern const asn_INTEGER_specifics_t asn_SPC_FANSToFrom_specs_1;
asn_struct_free_f FANSToFrom_free;
asn_struct_print_f FANSToFrom_print;
asn_constr_check_f FANSToFrom_constraint;
ber_type_decoder_f FANSToFrom_decode_ber;
der_type_encoder_f FANSToFrom_encode_der;
xer_type_decoder_f FANSToFrom_decode_xer;
xer_type_encoder_f FANSToFrom_encode_xer;
jer_type_encoder_f FANSToFrom_encode_jer;
oer_type_decoder_f FANSToFrom_decode_oer;
oer_type_encoder_f FANSToFrom_encode_oer;
per_type_decoder_f FANSToFrom_decode_uper;
per_type_encoder_f FANSToFrom_encode_uper;
per_type_decoder_f FANSToFrom_decode_aper;
per_type_encoder_f FANSToFrom_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSToFrom_H_ */
#include <asn_internal.h>
