/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSIcing.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_FANSIcing_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_FANSIcing_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_FANSIcing_value2enum_1[] = {
	{ 0,	5,	"trace" },
	{ 1,	5,	"light" },
	{ 2,	8,	"moderate" },
	{ 3,	6,	"severe" }
};
static const unsigned int asn_MAP_FANSIcing_enum2value_1[] = {
	1,	/* light(1) */
	2,	/* moderate(2) */
	3,	/* severe(3) */
	0	/* trace(0) */
};
const asn_INTEGER_specifics_t asn_SPC_FANSIcing_specs_1 = {
	asn_MAP_FANSIcing_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_FANSIcing_enum2value_1,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_FANSIcing_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FANSIcing = {
	"FANSIcing",
	"FANSIcing",
	&asn_OP_NativeEnumerated,
	asn_DEF_FANSIcing_tags_1,
	sizeof(asn_DEF_FANSIcing_tags_1)
		/sizeof(asn_DEF_FANSIcing_tags_1[0]), /* 1 */
	asn_DEF_FANSIcing_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSIcing_tags_1)
		/sizeof(asn_DEF_FANSIcing_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_FANSIcing_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_FANSIcing_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_FANSIcing_specs_1	/* Additional specs */
};

