/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSFrequencyuhf_H_
#define	_FANSFrequencyuhf_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FANSFrequencyuhf */
typedef long	 FANSFrequencyuhf_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSFrequencyuhf_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSFrequencyuhf;
asn_struct_free_f FANSFrequencyuhf_free;
asn_struct_print_f FANSFrequencyuhf_print;
asn_constr_check_f FANSFrequencyuhf_constraint;
ber_type_decoder_f FANSFrequencyuhf_decode_ber;
der_type_encoder_f FANSFrequencyuhf_encode_der;
xer_type_decoder_f FANSFrequencyuhf_decode_xer;
xer_type_encoder_f FANSFrequencyuhf_encode_xer;
jer_type_encoder_f FANSFrequencyuhf_encode_jer;
oer_type_decoder_f FANSFrequencyuhf_decode_oer;
oer_type_encoder_f FANSFrequencyuhf_encode_oer;
per_type_decoder_f FANSFrequencyuhf_decode_uper;
per_type_encoder_f FANSFrequencyuhf_encode_uper;
per_type_decoder_f FANSFrequencyuhf_decode_aper;
per_type_encoder_f FANSFrequencyuhf_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSFrequencyuhf_H_ */
#include <asn_internal.h>
