/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSPositionCurrent_H_
#define	_FANSPositionCurrent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPositionCurrent */
typedef FANSPosition_t	 FANSPositionCurrent_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSPositionCurrent_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionCurrent;
asn_struct_free_f FANSPositionCurrent_free;
asn_struct_print_f FANSPositionCurrent_print;
asn_constr_check_f FANSPositionCurrent_constraint;
ber_type_decoder_f FANSPositionCurrent_decode_ber;
der_type_encoder_f FANSPositionCurrent_encode_der;
xer_type_decoder_f FANSPositionCurrent_decode_xer;
xer_type_encoder_f FANSPositionCurrent_encode_xer;
jer_type_encoder_f FANSPositionCurrent_encode_jer;
oer_type_decoder_f FANSPositionCurrent_decode_oer;
oer_type_encoder_f FANSPositionCurrent_encode_oer;
per_type_decoder_f FANSPositionCurrent_decode_uper;
per_type_encoder_f FANSPositionCurrent_encode_uper;
per_type_decoder_f FANSPositionCurrent_decode_aper;
per_type_encoder_f FANSPositionCurrent_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPositionCurrent_H_ */
#include "asn_internal.h"
