/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSATCDownlinkMessage_H_
#define	_FANSATCDownlinkMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSATCMessageHeader.h"
#include "FANSATCDownlinkMsgElementId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSATCDownlinkMsgElementIdSequence;

/* FANSATCDownlinkMessage */
typedef struct FANSATCDownlinkMessage {
	FANSATCMessageHeader_t	 aTCMessageheader;
	FANSATCDownlinkMsgElementId_t	 aTCDownlinkmsgelementid;
	struct FANSATCDownlinkMsgElementIdSequence	*aTCdownlinkmsgelementid_seqOf;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSATCDownlinkMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSATCDownlinkMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSATCDownlinkMessage_H_ */
#include <asn_internal.h>
