/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSSSREquipmentAvailable_H_
#define	_FANSSSREquipmentAvailable_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSSSREquipmentAvailable {
	FANSSSREquipmentAvailable_nnil	= 0,
	FANSSSREquipmentAvailable_atransponderModeA	= 1,
	FANSSSREquipmentAvailable_ctransponderModeAandC	= 2,
	FANSSSREquipmentAvailable_xtransponderModeS	= 3,
	FANSSSREquipmentAvailable_ptransponderModeSPA	= 4,
	FANSSSREquipmentAvailable_itransponderModeSID	= 5,
	FANSSSREquipmentAvailable_stransponderModeSPAID	= 6
} e_FANSSSREquipmentAvailable;

/* FANSSSREquipmentAvailable */
typedef long	 FANSSSREquipmentAvailable_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FANSSSREquipmentAvailable_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FANSSSREquipmentAvailable;
extern const asn_INTEGER_specifics_t asn_SPC_FANSSSREquipmentAvailable_specs_1;
asn_struct_free_f FANSSSREquipmentAvailable_free;
asn_struct_print_f FANSSSREquipmentAvailable_print;
asn_constr_check_f FANSSSREquipmentAvailable_constraint;
ber_type_decoder_f FANSSSREquipmentAvailable_decode_ber;
der_type_encoder_f FANSSSREquipmentAvailable_encode_der;
xer_type_decoder_f FANSSSREquipmentAvailable_decode_xer;
xer_type_encoder_f FANSSSREquipmentAvailable_encode_xer;
jer_type_encoder_f FANSSSREquipmentAvailable_encode_jer;
oer_type_decoder_f FANSSSREquipmentAvailable_decode_oer;
oer_type_encoder_f FANSSSREquipmentAvailable_encode_oer;
per_type_decoder_f FANSSSREquipmentAvailable_decode_uper;
per_type_encoder_f FANSSSREquipmentAvailable_encode_uper;
per_type_decoder_f FANSSSREquipmentAvailable_decode_aper;
per_type_encoder_f FANSSSREquipmentAvailable_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSSSREquipmentAvailable_H_ */
#include <asn_internal.h>
