/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#include "FANSATWAlongTrackWaypoint.h"

asn_TYPE_member_t asn_MBR_FANSATWAlongTrackWaypoint_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSATWAlongTrackWaypoint, position),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_FANSPosition,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"position"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSATWAlongTrackWaypoint, aTWdistance),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSATWDistance,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"aTWdistance"
		},
	{ ATF_POINTER, 2, offsetof(struct FANSATWAlongTrackWaypoint, speed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_FANSSpeed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"speed"
		},
	{ ATF_POINTER, 1, offsetof(struct FANSATWAlongTrackWaypoint, aTWaltitudesequence),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSATWAltitudeSequence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"aTWaltitudesequence"
		},
};
static const int asn_MAP_FANSATWAlongTrackWaypoint_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_FANSATWAlongTrackWaypoint_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSATWAlongTrackWaypoint_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* position */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aTWdistance */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* speed */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* aTWaltitudesequence */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSATWAlongTrackWaypoint_specs_1 = {
	sizeof(struct FANSATWAlongTrackWaypoint),
	offsetof(struct FANSATWAlongTrackWaypoint, _asn_ctx),
	asn_MAP_FANSATWAlongTrackWaypoint_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_FANSATWAlongTrackWaypoint_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSATWAlongTrackWaypoint = {
	"FANSATWAlongTrackWaypoint",
	"FANSATWAlongTrackWaypoint",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSATWAlongTrackWaypoint_tags_1,
	sizeof(asn_DEF_FANSATWAlongTrackWaypoint_tags_1)
		/sizeof(asn_DEF_FANSATWAlongTrackWaypoint_tags_1[0]), /* 1 */
	asn_DEF_FANSATWAlongTrackWaypoint_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSATWAlongTrackWaypoint_tags_1)
		/sizeof(asn_DEF_FANSATWAlongTrackWaypoint_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSATWAlongTrackWaypoint_1,
	4,	/* Elements count */
	&asn_SPC_FANSATWAlongTrackWaypoint_specs_1	/* Additional specs */
};

