/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSWinds.h"

asn_TYPE_member_t asn_MBR_FANSWinds_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSWinds, windDirection),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_FANSWindDirection,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"windDirection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSWinds, windSpeed),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_FANSWindSpeed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"windSpeed"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSWinds_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSWinds_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* windDirection */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* windSpeedEnglish */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* windSpeedMetric */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSWinds_specs_1 = {
	sizeof(struct FANSWinds),
	offsetof(struct FANSWinds, _asn_ctx),
	asn_MAP_FANSWinds_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSWinds = {
	"FANSWinds",
	"FANSWinds",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSWinds_tags_1,
	sizeof(asn_DEF_FANSWinds_tags_1)
		/sizeof(asn_DEF_FANSWinds_tags_1[0]), /* 1 */
	asn_DEF_FANSWinds_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSWinds_tags_1)
		/sizeof(asn_DEF_FANSWinds_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSWinds_1,
	2,	/* Elements count */
	&asn_SPC_FANSWinds_specs_1	/* Additional specs */
};

