/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSLatitude.h"

asn_TYPE_member_t asn_MBR_FANSLatitude_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSLatitude, latitudeDegrees),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_FANSLatitudeDegrees,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"latitudeDegrees"
		},
	{ ATF_POINTER, 1, offsetof(struct FANSLatitude, minutesLatLon),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_FANSMinutesLatLon,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"minutesLatLon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSLatitude, latitudeDirection),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_FANSLatitudeDirection,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"latitudeDirection"
		},
};
static const int asn_MAP_FANSLatitude_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_FANSLatitude_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSLatitude_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* latitudeDegrees */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 }, /* minutesLatLon */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 2, 0, 0 } /* latitudeDirection */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSLatitude_specs_1 = {
	sizeof(struct FANSLatitude),
	offsetof(struct FANSLatitude, _asn_ctx),
	asn_MAP_FANSLatitude_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_FANSLatitude_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSLatitude = {
	"FANSLatitude",
	"FANSLatitude",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSLatitude_tags_1,
	sizeof(asn_DEF_FANSLatitude_tags_1)
		/sizeof(asn_DEF_FANSLatitude_tags_1[0]), /* 1 */
	asn_DEF_FANSLatitude_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSLatitude_tags_1)
		/sizeof(asn_DEF_FANSLatitude_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSLatitude_1,
	3,	/* Elements count */
	&asn_SPC_FANSLatitude_specs_1	/* Additional specs */
};

