/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#ifndef	_FANSRTARequiredTimeArrival_H_
#define	_FANSRTARequiredTimeArrival_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSRTATime.h"
#include "FANSRTATolerance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FANSRTARequiredTimeArrival */
typedef struct FANSRTARequiredTimeArrival {
	FANSPosition_t	 position;
	FANSRTATime_t	 rTATime;
	FANSRTATolerance_t	*rTATolerance;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRTARequiredTimeArrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRTARequiredTimeArrival;
extern asn_SEQUENCE_specifics_t asn_SPC_FANSRTARequiredTimeArrival_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSRTARequiredTimeArrival_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRTARequiredTimeArrival_H_ */
#include <asn_internal.h>
