/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/fans-cpdlc.asn1"
 * 	`asn1c -fincludes-quoted -fcompound-names -no-gen-example -D /data/libacars/libacars/libacars/asn1`
 */

#ifndef	_FANSCOMNAVEquipmentStatusSequence_H_
#define	_FANSCOMNAVEquipmentStatusSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSCOMNAVEquipmentStatus.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSCOMNAVEquipmentStatusSequence */
typedef struct FANSCOMNAVEquipmentStatusSequence {
	A_SEQUENCE_OF(FANSCOMNAVEquipmentStatus_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSCOMNAVEquipmentStatusSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSCOMNAVEquipmentStatusSequence;
extern asn_SET_OF_specifics_t asn_SPC_FANSCOMNAVEquipmentStatusSequence_specs_1;
extern asn_TYPE_member_t asn_MBR_FANSCOMNAVEquipmentStatusSequence_1[1];
extern asn_per_constraints_t asn_PER_type_FANSCOMNAVEquipmentStatusSequence_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSCOMNAVEquipmentStatusSequence_H_ */
#include "asn_internal.h"
