/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "/data/asn1_specs/szpajder.libacars/fans-cpdlc.asn1"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-example -D /data/asn1_specs/szpajder.libacars/generated/fans-cpdlc.asn1`
 */

#include "FANSRemainingFuelRemainingSouls.h"

asn_TYPE_member_t asn_MBR_FANSRemainingFuelRemainingSouls_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSRemainingFuelRemainingSouls, remainingFuel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSRemainingFuel,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"remainingFuel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSRemainingFuelRemainingSouls, remainingSouls),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_FANSRemainingSouls,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"remainingSouls"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSRemainingFuelRemainingSouls_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSRemainingFuelRemainingSouls_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* remainingSouls */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* remainingFuel */
};
asn_SEQUENCE_specifics_t asn_SPC_FANSRemainingFuelRemainingSouls_specs_1 = {
	sizeof(struct FANSRemainingFuelRemainingSouls),
	offsetof(struct FANSRemainingFuelRemainingSouls, _asn_ctx),
	asn_MAP_FANSRemainingFuelRemainingSouls_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FANSRemainingFuelRemainingSouls = {
	"FANSRemainingFuelRemainingSouls",
	"FANSRemainingFuelRemainingSouls",
	&asn_OP_SEQUENCE,
	asn_DEF_FANSRemainingFuelRemainingSouls_tags_1,
	sizeof(asn_DEF_FANSRemainingFuelRemainingSouls_tags_1)
		/sizeof(asn_DEF_FANSRemainingFuelRemainingSouls_tags_1[0]), /* 1 */
	asn_DEF_FANSRemainingFuelRemainingSouls_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSRemainingFuelRemainingSouls_tags_1)
		/sizeof(asn_DEF_FANSRemainingFuelRemainingSouls_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FANSRemainingFuelRemainingSouls_1,
	2,	/* Elements count */
	&asn_SPC_FANSRemainingFuelRemainingSouls_specs_1	/* Additional specs */
};

